config/routes.rb
Rails.application.routes.draw do
  get "student_temporary/index", as: "student_temporary"
  post "student/tempo/generate", to: "student_temporary#generate_pdf", as: "generate_student_tempo"
  get "pdf_grade_reports/index", as: "pdf_gread_report"
  get "prepare_pdf.pdf", to: "pdf_grade_reports#prepare_pdf"
  get "student/tempo/generate.pdf", to: "student_temporary#generate_pdf"
  get "graduation/approval", to: "student_temporary#graduation_approval", as: "graduation_approval"
  get "graduation/approval/form", to: "student_temporary#graduation_approval_form", as: "graduation_approval_form"
  get "approved", to: "student_temporary#approved", as: "approved"
  get "student/generate/copy", to: "student_copy#index", as: "student_copy"
  post "student_copy/generate_student_copy", as: "generate_student_copy"
  get "new/semester/registration", to: "pages#enrollement", as: "enrollement"
  post "create/semester/registration", to: "pages#create_semester_registration", as: "create_semester_registration"
  get "student/grade/report/:year/:semester", to: "grade_reports#student_grade_report", as: "student_grade_report"
  get "prepare/payment/:semester_registration_id", to: "invoices#prepare_payment", as: "prepare_payment"
  post "create/invoice", to: "invoices#create_invoice_for_remaining_amount", as: "create_invoice_for_remaining_amount"
  get "payment/report/fetch/student", to: "payment_report#fetch_student", as: "payment_report_fetch_student"
  get "get/year", to: "payment_report#get_year", as: "payment_report_get_year"
  get "get/semester", to: "payment_report#get_semester", as: "payment_report_get_semester"
  get "student/report", to: "student_report#get_student_list", as: "student_report"
  get "/student/report/year", to: "student_report#student_report_year", as: "student_report_year"
  get "/student/report/program", to: "student_report#student_report_program", as: "student_report_program"
  get "/student/gc/program", to: "student_report#student_report_gc", as: "student_report_gc"
  get "/student/report/gc/year", to: "student_report#student_report_gc_year", as: "student_report_gc_year"
  get "/student/report/semester", to: "student_report#student_report_semester", as: "student_report_semester"
  get "/prepare/online/student/grade", to: "online_student_grade#prepare", as: "online_student_grade_prepare"
  post "/student/pdf/report.pdf", to: "student_report#student_report_pdf", as: "student_report_pdf"
  post "generate/payment/report.pdf", to: "payment_report#generate_payment_report", as: "generate_payment_report"
  get "/online/student/grade", to: "online_student_grade#online_grade", as: "online_grade"
  post "/approve/online/student/grade", to: "online_student_grade#approve_grade", as: "approve_online_grade"
  resources :grade_reports
  resources :academic_calendars, only: [:show, :index]
  devise_for :students, controllers: {
                          registrations: "registrations",
                        }
  authenticated :student do
    root "pages#dashboard", as: "authenticated_user_root"
  end
  devise_scope :student do
    put "update/highschool/transcript", to: "registrations#update_highschool_transcript", as: "update_highschool_transcript"
    put "update/grade/10/matric", to: "registrations#update_grade_10_matric", as: "update_grade_10_matric"
    put "update/grade/12/matric", to: "registrations#update_grade_12_matric", as: "update_grade_12_matric"
    put "update/coc", to: "registrations#update_coc", as: "update_coc"
    put "update/profile/photo", to: "registrations#update_profile_photo", as: "update_profile_photo"
    put "update/diploma/certificate", to: "registrations#update_diploma_certificate", as: "update_diploma_certificate"
    put "update/degree/certificate", to: "registrations#update_degree_certificate", as: "update_degree_certificate"
  end

  post "prepare_pdf", to: "pdf_grade_reports#prepare_pdf", as: "prepare_pdf"
  get "admission" => "pages#admission"
  get "documents" => "pages#documents", as: "documents"
  get "profile" => "pages#profile", as: "profile"
  get "grade_report" => "pages#grade_report"
  get "digital-iteracy-quiz" => "pages#digital_iteracy_quiz"
  get "requirements" => "pages#requirement"
  get "home" => "pages#home"
  resources :almunis
  resources :semester_registrations
  resources :invoices
  resources :profiles

  resources :payment_methods
  resources :payment_transactions
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root to: 'application#home'
end

app/controllers/payment_transactions_controller.rb
class PaymentTransactionsController < ApplicationController
  before_action :set_payment_transaction, only: %i[ show edit update destroy ]

  # GET /payment_transactions or /payment_transactions.json
  def index
    @payment_transactions = PaymentTransaction.all
  end

  # GET /payment_transactions/1 or /payment_transactions/1.json
  def show
  end

  # GET /payment_transactions/new
  def new
    @payment_transaction = PaymentTransaction.new
    @payment_method = PaymentMethod.find(params[:payment_method_id])
    @invoice = Invoice.find(params[:invoice_id])
  end

  # GET /payment_transactions/1/edit
  def edit
    @payment_method = @payment_transaction.payment_method
    @invoice = @payment_transaction.invoice
  end

  # POST /payment_transactions or /payment_transactions.json
  def create
    @payment_transaction = PaymentTransaction.new(payment_transaction_params)

    respond_to do |format|
      if @payment_transaction.save
        format.html { redirect_to invoice_path(@payment_transaction.invoiceable), notice: "Payment transaction was successfully created." }
        format.json { render :show, status: :created, location: @payment_transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_transactions/1 or /payment_transactions/1.json
  def update
    respond_to do |format|
      if @payment_transaction.update(payment_transaction_params)
        format.html { redirect_to @payment_transaction, notice: "Payment transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @payment_transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_transactions/1 or /payment_transactions/1.json
  def destroy
    @payment_transaction.destroy
    respond_to do |format|
      format.html { redirect_to payment_transactions_url, notice: "Payment transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_transaction
      @payment_transaction = PaymentTransaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_transaction_params
      params.fetch(:payment_transaction, {}).permit(:invoiceable_type, :invoiceable_id, :payment_method_id,:account_holder_fullname,:phone_number,:account_number,:transaction_reference,:finance_approval_status,:last_updated_by,:created_by, :receipt_image)
    end
end

app/helpers/payment_transactions_helper.rb
module PaymentTransactionsHelper
end

app/views/payment_transactions/_form.html.erb
<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-12">
				<div class="card card card-primary">
					<div class="card-header">
						<h3 class="card-title">
							<i class="fas fa-edit"></i>
							Payment Form
						</h3>
					</div>
					<div class="card-body p-0">
						<div class="bs-stepper">
							<div class="bs-stepper-header" role="tablist">
								<!-- your steps here -->
								<div class="step" data-target="#bi">
									<button type="button" class="step-trigger" role="tab" aria-controls="logins-part" id="bi-trigger">
										<span class="bs-stepper-circle">1</span>
										<span class="bs-stepper-label">Payment Transfer Detail</span>
									</button>
								</div>
								<div class="line"></div>
								<div class="step" data-target="#admission">
									<button type="button" class="step-trigger" role="tab" aria-controls="admission" id="admission-trigger">
										<span class="bs-stepper-circle">2</span>
										<span class="bs-stepper-label">Payment Form</span>
									</button>
								</div>
							</div>
							
							<%= simple_form_for(@payment_transaction, local: true) do |f| %>
							  <%= f.error_notification %>
							  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
							  <%=f.input :invoiceable_type, as: :hidden, :input_html => { :value => "Invoice"}%>
							  <%=f.input :invoiceable_id, as: :hidden, :input_html => { :value => params[:invoice_id]}%>
                  <%=f.input :payment_method_id, as: :hidden, :input_html => { :value => params[:payment_method_id]}%>
								<div class="bs-stepper-content">
									<!-- your steps content here -->
									<div id="bi" class="content" role="tabpanel" aria-labelledby="bi-trigger">
										<div class="row">
											<div class="col-12 col-md-4">
												<div class="card card-outline card-primary">
													<div class="card-header">
														<h3 class="card-title">
															<i class="fas fa-info-circle mr-2"></i>
															<strong>Instruction</strong>

														</h3>
													</div>
													<!-- /.card-header -->
													<div class="card-body">
														<p  class="text-center"><strong>Please, transfer <%=(@invoice.total_price + @invoice.registration_fee) if @invoice.present?%> ETB to the account we provide you and fill the form with in your bank information.</strong></p>   
														<hr>
													</div>
													<!-- /.card-body -->
												</div>
											</div>

											<%if PaymentMethod.find_by(id: params[:payment_method_id]).present?%>
											<div class="col-12 col-md-8">
												<div class="card card-primary card-outline">
						              <div class="card-body box-profile">
						                <div class="text-center">
						                	
						                  	<%= image_tag(@payment_method.bank_logo, class: "profile-user-img img-fluid")%>
						                  
						                </div>

						                <h3 class="profile-username text-center"><%= @payment_method.bank_name%></h3>

						                <p class="text-muted text-center"><%= @payment_method.payment_method_type%></p>

						                <ul class="list-group list-group-unbordered mb-3">
								              <li class="list-group-item mx-3">
								                <b>Account Name</b> <a class="text-muted float-right"><%= @payment_method.account_full_name%></a>
								              </li>
								              <li class="list-group-item mx-3">
								                <b>Account Number</b> <a class="text-muted float-right"><%= @payment_method.account_number%></a>
								              </li>
								              <li class="list-group-item mx-3">
								                <b>Bank Name</b> <a class="text-muted float-right"><%= @payment_method.bank_name%></a>
								              </li>
								              <li class="list-group-item mx-3">
								                <b>Phone Number</b> <a class="text-muted float-right"><%= @payment_method.phone_number%></a>
								              </li>
								            </ul>
						                <a class="btn btn-primary btn-block" onclick="stepper.next()">Continue</a>
						              </div>
						              <!-- /.card-body -->
						            </div>
												
											</div>
											<%end%>
											
										</div>
									</div>
									<div id="admission" class="content" role="tabpanel" aria-labelledby="admission-trigger">
										<div class="row">
											<div class="col-12 col-md-3">
												<div class="card card-outline card-primary">
													<div class="card-header">
														<h3 class="card-title">
															<i class="fas fa-info-circle mr-2"></i>
															<strong>Instruction</strong>

														</h3>
													</div>
													<!-- /.card-header -->
													<div class="card-body">
														<p  class="text-center"><strong>Fill in the space(s) or Select the appropriate box(es) or selctions. * fields are required.</strong></p>  
														<p class="text-muted text-center">
															You must provide your address information on the fields provided. Once you fill all the required feilds hit the Continue button.
														</p>
														<hr>
													</div>
													<!-- /.card-body -->
												</div>
											</div>
											<div class="col-12 col-md-9">
												<div class="card card-outline card-primary">
													<div class="card-header">
														<h3 class="card-title">
															<i class="fas fa-info-circle mr-2"></i>
															<strong>Payment Form</strong>
														</h3>
													</div>
													<div class="card-body row">
														<div class="col-12 col-md-6 form-group">
												      <%= f.input :account_holder_fullname, input_html: { class: 'form-control', autofocus: true, autocomplete: "account_holder_fullname", id: "accountfullname" },placeholder: "Account holder f ullname", required: true %>
												    </div>
												    <div class="col-12 col-md-6 form-group">
												      <%= f.input :account_number, input_html: { class: 'form-control', autocomplete: "account_number", id: "accountnumber" },placeholder: "Account number", required: true %>
												    </div>
												    <div class="col-12 col-md-6 form-group">
												      <%= f.input :phone_number, input_html: { class: 'form-control', autocomplete: "phone_number", id: "accountphone" },placeholder: "Phone number", required: true %>
												    </div>
												    <div class="col-12 col-md-6 form-group">
												      <%= f.input :transaction_reference, input_html: { class: 'form-control', autocomplete: "transaction_reference", id: "accountreference" },placeholder: "Transaction Reference", required: true %>
												    </div>
												    <div class="col-12 col-md-6 form-group">
												      <%= f.input :receipt_image, as: :file, required: true %>
												    </div>
													</div>
													<div class="card-footer">
														<a class="btn btn-secondary" onclick="stepper.previous()">Previous</a>
														<%= f.submit "Finish", class: "btn btn-primary btn-user" %>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							<% end %>
						</div>
					</div>
					<!-- /.card-body -->
				</div>
				<!-- /.card -->
			</div>
		</div>
	</div>
</div>

app/views/payment_transactions/edit.html.erb
<%provide(:title, "Update Payment information")%>

<section class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1>Update payment information</h1>
			</div>
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="/">Home</a></li>
					<li class="breadcrumb-item active">Inovices</li>
				</ol>
			</div>
		</div>
	</div><!-- /.container-fluid -->
</section>
<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-12">
				<div class="card card card-primary">
					<div class="card-header">
						<h3 class="card-title">
							<i class="fas fa-edit"></i>
							update Payment information
						</h3>
					</div>
					<div class="card-body p-0">
						<div class="bs-stepper">
							<div class="bs-stepper-header" role="tablist">
								<!-- your steps here -->
								<div class="step" data-target="#bi">
									<button type="button" class="step-trigger" role="tab" aria-controls="logins-part" id="bi-trigger">
										<span class="bs-stepper-circle">1</span>
										<span class="bs-stepper-label">Payment Transfer Detail</span>
									</button>
								</div>
								<div class="line"></div>
								<div class="step" data-target="#admission">
									<button type="button" class="step-trigger" role="tab" aria-controls="admission" id="admission-trigger">
										<span class="bs-stepper-circle">2</span>
										<span class="bs-stepper-label">Payment Form</span>
									</button>
								</div>
							</div>
							
							<%= simple_form_for(@payment_transaction) do |f| %>
							  <%= f.error_notification %>
							  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
							  <%=f.input :invoice_id, as: :hidden, :input_html => { :value => @invoice.id}%>
                  <%=f.input :payment_method_id, as: :hidden, :input_html => { :value => @payment_method.id}%>
								<div class="bs-stepper-content">
									<!-- your steps content here -->
									<div id="bi" class="content" role="tabpanel" aria-labelledby="bi-trigger">
										<div class="row">
											<div class="col-12 col-md-4">
												<div class="card card-outline card-primary">
													<div class="card-header">
														<h3 class="card-title">
															<i class="fas fa-info-circle mr-2"></i>
															<strong>Instruction</strong>

														</h3>
													</div>
													<!-- /.card-header -->
													<div class="card-body">
														<p  class="text-center"><strong>Please, transfer <%=Invoice.find_by(id: params[:invoice_id]).total_price if Invoice.find_by(id: params[:invoice_id]).total_price.present?%> ETB to the account we provide you and fill the form with in your bank information.</strong></p>  
														<hr>
													</div>
													<!-- /.card-body -->
												</div>
											</div>
											<div class="col-12 col-md-8">
												<div class="card card-primary card-outline">
						              <div class="card-body box-profile">
						                <div class="text-center">
						                  <%= image_tag(@payment_method.bank_logo, class: "profile-user-img img-fluid")%>
						                </div>

						                <h3 class="profile-username text-center"><%= @payment_method.bank_name%></h3>

						                <p class="text-muted text-center"><%= @payment_method.payment_method_type%></p>

						                <ul class="list-group list-group-unbordered mb-3">
								              <li class="list-group-item mx-3">
								                <b>Account Name</b> <a class="text-muted float-right"><%= @payment_method.account_full_name%></a>
								              </li>
								              <li class="list-group-item mx-3">
								                <b>Account Number</b> <a class="text-muted float-right"><%= @payment_method.account_number%></a>
								              </li>
								              <li class="list-group-item mx-3">
								                <b>Bank Name</b> <a class="text-muted float-right"><%= @payment_method.bank_name%></a>
								              </li>
								              <li class="list-group-item mx-3">
								                <b>Phone Number</b> <a class="text-muted float-right"><%= @payment_method.phone_number%></a>
								              </li>
								            </ul>
						                <a class="btn btn-primary btn-block" onclick="stepper.next()">Continue</a>
						              </div>
						              <!-- /.card-body -->
						            </div>
												
											</div>
											
										</div>
									</div>
									<div id="admission" class="content" role="tabpanel" aria-labelledby="admission-trigger">
										<div class="row">
											<div class="col-12 col-md-3">
												<div class="card card-outline card-primary">
													<div class="card-header">
														<h3 class="card-title">
															<i class="fas fa-info-circle mr-2"></i>
															<strong>Instruction</strong>

														</h3>
													</div>
													<!-- /.card-header -->
													<div class="card-body">
														<p  class="text-center"><strong>Fill in the space(s) or Select the appropriate box(es) or selctions. * fields are required.</strong></p>  
														<p class="text-muted text-center">
															You must provide your address information on the fields provided. Once you fill all the required feilds hit the Continue button.
														</p>
														<hr>
													</div>
													<!-- /.card-body -->
												</div>
											</div>
											<div class="col-12 col-md-9">
												<div class="card card-outline card-primary">
													<div class="card-header">
														<h3 class="card-title">
															<i class="fas fa-info-circle mr-2"></i>
															<strong>Payment Form</strong>
														</h3>
													</div>
													<div class="card-body row">
														<div class="col-12 col-md-6 form-group">
												      <%= f.input :account_holder_fullname, input_html: { class: 'form-control', autofocus: true, autocomplete: "account_holder_fullname" },placeholder: "Account holder f ullname", required: true %>
												    </div>
												    <div class="col-12 col-md-6 form-group">
												      <%= f.input :account_number, input_html: { class: 'form-control', autocomplete: "account_number" },placeholder: "Account number", required: true %>
												    </div>
												    <div class="col-12 col-md-6 form-group">
												      <%= f.input :phone_number, input_html: { class: 'form-control', autocomplete: "phone_number" },placeholder: "Phone number", required: true %>
												    </div>
												    <div class="col-12 col-md-6 form-group">
												      <%= f.input :transaction_reference, input_html: { class: 'form-control', autocomplete: "transaction_reference" },placeholder: "Transaction Reference", required: true %>
												    </div>
												    <div class="col-12 col-md-6 form-group">
												      <%= f.input :receipt_image, as: :file, required: true %>
												    </div>
													</div>
													<div class="card-footer">
														<a class="btn btn-secondary" onclick="stepper.previous()">Previous</a>
														<%= f.submit "Finish", class: "btn btn-primary btn-user" %>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							<% end %>
						</div>
					</div>
					<!-- /.card-body -->
				</div>
				<!-- /.card -->
			</div>
		</div>
	</div>
</div>

app/views/payment_transactions/index.html.erb
<h1>Payment Transactions</h1>

<table class="responsive nowrap table table-hover" id="dttb-payment_transactions" data-sort="true" data-source="<%= url_for(format: :json)%>">
  <thead>
    <tr>
      <th data-data="url" data-orderable="false" data-class-name="all" data-searchable="false" class="skip-export" width="100px"></th>
    </tr>
  </thead>

</table>

<br>

<%= link_to 'New Payment Transaction', new_payment_transaction_path %>

app/views/payment_transactions/new.html.erb
<%provide(:title, "Payment MTransfer")%>

<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Payment Form</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item"><a href="/">Invoices</a></li>
          <li class="breadcrumb-item active">Payment Form</li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>

<%= render 'form', payment_transaction: @payment_transaction %>

app/views/payment_transactions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_payment_transaction_path(@payment_transaction) %> |
<%= link_to 'Back', payment_transactions_path %>