config/routes.rb
Rails.application.routes.draw do
  get "student_temporary/index", as: "student_temporary"
  post "student/tempo/generate", to: "student_temporary#generate_pdf", as: "generate_student_tempo"
  get "pdf_grade_reports/index", as: "pdf_gread_report"
  get "prepare_pdf.pdf", to: "pdf_grade_reports#prepare_pdf"
  get "student/tempo/generate.pdf", to: "student_temporary#generate_pdf"
  get "graduation/approval", to: "student_temporary#graduation_approval", as: "graduation_approval"
  get "graduation/approval/form", to: "student_temporary#graduation_approval_form", as: "graduation_approval_form"
  get "approved", to: "student_temporary#approved", as: "approved"
  get "student/generate/copy", to: "student_copy#index", as: "student_copy"
  post "student_copy/generate_student_copy", as: "generate_student_copy"
  get "new/semester/registration", to: "pages#enrollement", as: "enrollement"
  post "create/semester/registration", to: "pages#create_semester_registration", as: "create_semester_registration"
  get "student/grade/report/:year/:semester", to: "grade_reports#student_grade_report", as: "student_grade_report"
  get "prepare/payment/:semester_registration_id", to: "invoices#prepare_payment", as: "prepare_payment"
  post "create/invoice", to: "invoices#create_invoice_for_remaining_amount", as: "create_invoice_for_remaining_amount"
  get "payment/report/fetch/student", to: "payment_report#fetch_student", as: "payment_report_fetch_student"
  get "get/year", to: "payment_report#get_year", as: "payment_report_get_year"
  get "get/semester", to: "payment_report#get_semester", as: "payment_report_get_semester"
  get "student/report", to: "student_report#get_student_list", as: "student_report"
  get "/student/report/year", to: "student_report#student_report_year", as: "student_report_year"
  get "/student/report/program", to: "student_report#student_report_program", as: "student_report_program"
  get "/student/gc/program", to: "student_report#student_report_gc", as: "student_report_gc"
  get "/student/report/gc/year", to: "student_report#student_report_gc_year", as: "student_report_gc_year"
  get "/student/report/semester", to: "student_report#student_report_semester", as: "student_report_semester"
  get "/prepare/online/student/grade", to: "online_student_grade#prepare", as: "online_student_grade_prepare"
  post "/student/pdf/report.pdf", to: "student_report#student_report_pdf", as: "student_report_pdf"
  post "generate/payment/report.pdf", to: "payment_report#generate_payment_report", as: "generate_payment_report"
  get "/online/student/grade", to: "online_student_grade#online_grade", as: "online_grade"
  post "/approve/online/student/grade", to: "online_student_grade#approve_grade", as: "approve_online_grade"
  resources :grade_reports
  resources :academic_calendars, only: [:show, :index]
  devise_for :students, controllers: {
                          registrations: "registrations",
                        }
  authenticated :student do
    root "pages#dashboard", as: "authenticated_user_root"
  end
  devise_scope :student do
    put "update/highschool/transcript", to: "registrations#update_highschool_transcript", as: "update_highschool_transcript"
    put "update/grade/10/matric", to: "registrations#update_grade_10_matric", as: "update_grade_10_matric"
    put "update/grade/12/matric", to: "registrations#update_grade_12_matric", as: "update_grade_12_matric"
    put "update/coc", to: "registrations#update_coc", as: "update_coc"
    put "update/profile/photo", to: "registrations#update_profile_photo", as: "update_profile_photo"
    put "update/diploma/certificate", to: "registrations#update_diploma_certificate", as: "update_diploma_certificate"
    put "update/degree/certificate", to: "registrations#update_degree_certificate", as: "update_degree_certificate"
  end

  post "prepare_pdf", to: "pdf_grade_reports#prepare_pdf", as: "prepare_pdf"
  get "admission" => "pages#admission"
  get "documents" => "pages#documents", as: "documents"
  get "profile" => "pages#profile", as: "profile"
  get "grade_report" => "pages#grade_report"
  get "digital-iteracy-quiz" => "pages#digital_iteracy_quiz"
  get "requirements" => "pages#requirement"
  get "home" => "pages#home"
  resources :almunis
  resources :semester_registrations
  resources :invoices
  resources :profiles

  resources :payment_methods
  resources :payment_transactions
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root to: 'application#home'
end

app/models/program.rb
class Program < ApplicationRecord
  # before_save :update_subtotal
  before_save :total_semester_calc
  

	##validations
    validates :program_name , :presence => true,:length => { :within => 2..50 }
    validates :study_level , :presence => true
    validates :admission_type , :presence => true
    validates :program_duration , :presence => true
    validates :program_semester , :presence => true
    validates :program_code, :presence => true
    # validates :total_semester, :presence => true
  ##scope
  	scope :recently_added, lambda { where('created_at >= ?', 1.week.ago)}
  	scope :undergraduate, lambda { where(study_level: "undergraduate")}
  	scope :graduate, lambda { where(study_level: "graduate")}
  	scope :online, lambda { where(admission_type: "online")}
  	scope :regular, lambda { where(admission_type: "regular")}
  	scope :extention, lambda { where(admission_type: "extention")}
  	scope :distance, lambda { where(admission_type: "distance")}
  ##associations
    has_many :invoices
    has_many :withdrawals
    has_many :student_grades
    has_many :grade_changes
    has_many :grade_reports
    has_many :sections, dependent: :destroy
    has_many :courses
    belongs_to :department
    has_many :grade_systems, dependent: :destroy
    has_many :attendances
    has_many :students
    has_many :semester_registrations
    has_many :course_registrations
    has_many :curriculums, dependent: :destroy
    accepts_nested_attributes_for :curriculums, reject_if: :all_blank, allow_destroy: true
    has_many :recurring_payments
    has_many :add_and_drops
    has_many :makeup_exams
    has_many :payments
  
  # def total_tuition
  #   curriculums.collect { |oi| oi.valid? ? (oi.full_course_price) : 0 }.sum
  # end

  def total_semester
    total_semester = program_semester * program_duration
  end
  private

  # def update_subtotal
  #   self[:total_tuition] = total_tuition
  # end
  def total_semester_calc
    self[:total_semester] = total_semester
  end
end

app/controllers/student_temporary_controller.rb
class StudentTemporaryController < ApplicationController
  add_flash_types :success

  def index
    @disable_nav = true
    @program = Program.select(:program_name, :id)
  end

  def approved
    ids = session[:student_ids]
    graduation_status = Student.where(id: ids).update(graduation_status: "approved", graduation_year: Date.current.year)
    if graduation_status
      redirect_to admin_graduation_url, notice: "#{ids.size} #{"student".pluralize(ids.size)} got approved for graduation"
    else
      redirect_to graduation_approval_form_url, alert: "Something went wrong for the selected student"
    end
  end

  def graduation_approval
    program_id = params[:program][:name]
    study = params[:study]
    program = Program.find(program_id)
    student_ids = filter_student(program, study)
    if student_ids.empty?
      redirect_to graduation_approval_form_url, alert: "We could not find a student matching your search criteria"
    else
      session[:student_ids] = student_ids
      redirect_to graduation_approval_form_url, success: "#{student_ids.size} #{"student".pluralize(student_ids.size)} in #{program.program_name} program with #{study} study level are ready for graduation"
    end
  end

  def graduation_approval_form
    @disable_nav = true
    @program = Program.select(:program_name, :id)
  end

  def generate_pdf
    program_id = params[:program][:name]
    degree = params[:degree]
    gc_date = params[:gc][:date]
    study = params[:study]

    program = Program.find(program_id)
    students = filter_student_for_tempo(program, study)
    redirect_to student_temporary_url, alert: "We could not find a student matching your search criteria. Please please check student graduation status is approved" if students.empty?
    if students.any?
      respond_to do |format|
        format.html
        format.pdf do
          pdf = StudentTemporary.new(students, degree, gc_date)
          send_data pdf.render, filename: "#{study}_#{program.program_name}_program.pdf", type: "application/pdf", disposition: "inline"
        end
      end
    end
  end

  private

  def filter_student(program, study)
    grade_system = GradeSystem.select(:min_cgpa_value_to_graduate).find_by(program: program)
    curriculum = Curriculum.select(:total_course).find_by(program: program)
    min_cgpa_value_to_graduate = grade_system.min_cgpa_value_to_graduate if grade_system.present?
    students = Student.where(program: program).where(year: program.program_duration).where(graduation_status: "pending").where(semester: program.program_semester).where(study_level: study).includes(:grade_reports).includes(:student_grades)
    number_of_course_in_curriculum = curriculum.total_course if curriculum.present?
    all_student_ids = []
    students.each do |stud|
      total_course = stud.grade_reports.last.total_course if stud.grade_reports.last.present?
      cgpa = stud.grade_reports.last.cgpa if stud.grade_reports.last.present?
      major = Major.major_point_and_hour(stud.course_registrations)
      if study == "undergraduate"
        number_of_f = stud.student_grades.where(letter_grade: "F").where(letter_grade: "f").size
        if total_course == number_of_course_in_curriculum && cgpa >= 2.0 && number_of_f == 0 && major[1] >= 2
          all_student_ids << stud.id
        end
      else
        number_of_c = stud.student_grades.where(letter_grade: "c").where(letter_grade: "C").size
        if total_course == number_of_course_in_curriculum && cgpa >= min_cgpa_value_to_graduate && number_of_c <= 2
          all_student_ids << stud.id
        end
      end
    end
    all_student_ids
  end

  def filter_student_for_tempo(program, study)
    students = Student.where(program: program).where(study_level: study).where(graduation_status: "approved").includes(:grade_reports).includes(:student_grades)
    students
  end
end

app/helpers/student_temporary_helper.rb
module StudentTemporaryHelper
end

app/views/student_temporary/graduation_approval_form.erb
<div class="filter-container">
 <h3 class="text-center text-bold text-underline">Student Graduation status approval form</h3>

 <%= form_tag(graduation_approval_path, method: 'get', class: 'search-form') do |form|%>
    <br>
    <div class="filed">
        <label>Program Name: </label>
        <%= collection_select(:program, :name, @program, :id, :program_name,  {prompt: 'Select a Department'}, required: true) %> 
    </div>

<div class="filed">
        <label>Study Level: </label>
      <select name="study" id="study" required="true">
        <option value="">Select study level</option>
        <option value="undergraduate"> Undergraduate </option>
        <option value="graduate"> Graduate </option>
      </select>
 </div>
    <div class="text-center">
      <input type="submit" value="Search student", class="btn btn-success">
    </div>
  <% end %>

<% if alert.present?%>
<div class="alert alert-warning" role="alert">
<%=alert%>
</div>
<%end%>
<%if success.present?%>
 <div class="alert alert-success text-center" role="alert">
  <p><%= success %> </p>
</div>
      <%# <input type="button" value="Search student", class="btn btn-success"> %>
      <%= link_to "Approve #{session[:student_ids].size} student for graduation", approved_path,  class: 'btn btn-success', data: { confirm: "Are you sure you want to approve the 
                    selected (#{session[:student_ids].size}) student?"}%>

<%end%> 
</div>

app/views/student_temporary/index.html.erb
<div class="filter-container">
 <h3 class="text-center text-bold text-underline">A student temporary preparation form</h3>

 <%= form_tag(generate_student_tempo_path(format: 'pdf'), method: 'post', class: 'search-form') do |form|%>
    <br>
    <div class="filed">
        <label>Program Name: </label>
        <%= collection_select(:program, :name, @program, :id, :program_name,  {prompt: 'Select a Department'}, required: true) %> 
    </div>
<div class="filed">
        <label>Degree Type: </label>
        <select name="degree" id="degree" required="true">
        <option value="">Select degree type</option>
        <option value="Bachelor of Science">Bachelor of Science </option>
        <option value="Bachelor of Art">Bachelor of Art</option>
        <option value="Bachelor of Education">Bachelor of Education </option>
        <option value="Master's of Science">Master's of Science</option>
        <option value="Master's of Art">Master's of Art</option>
        <option value="Doctor of Medicine">Doctor of Medicine</option>
        </select>
</div>

<div class="filed">
        <label>Study Level: </label>
        <select name="study" id="study" required="true">
        <option value="">Select study level</option>
        <option value="undergraduate"> Undergraduate </option>
        <option value="graduate"> Graduate </option>
        </select>
</div>

<div class="filed">
<label>Graduation Date: </label>
    <%= date_field :gc, :date, class: 'form-controvl', required: true %>

</div>

    <div class="text-center pt-2">
      <input type="submit" value="Generate Tempo", class="btn btn-success">
    </div>
  <% end %>

<% if alert.present?%>
<div class="alert alert-warning text-center" role="alert">
<%=alert%>
</div>
<%end%> 
</div>